files: "^backend/"
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
      - id: check-added-large-files
      - id: check-docstring-first
      - id: check-merge-conflict
      - id: check-symlinks
      - id: check-toml
      - id: check-xml
      - id: check-yaml
      - id: debug-statements
      - id: detect-private-key
      - id: end-of-file-fixer
      - id: mixed-line-ending
        args: ["--fix=lf"]
      - id: requirements-txt-fixer
      - id: trailing-whitespace

  - repo: local
    hooks:
      - id: isort
        name: isort
        entry: bash -c 'cd backend && poetry run isort --settings-path pyproject.toml "$@"'
        types: [python]
        language: system

  - repo: local
    hooks:
      - id: pyupgrade
        name: pyupgrade
        entry: bash -c 'cd backend && poetry run pyupgrade --py38-plus "$@"'
        types: [python]
        language: system

  - repo: local
    hooks:
      - id: black
        name: black
        entry: bash -c 'cd backend && poetry run black --config pyproject.toml "$@"'
        types: [python]
        language: system

  - repo: local
    hooks:
      - id: mypy
        name: mypy
        entry: bash -c 'cd backend && poetry run mypy --config-file pyproject.toml "$@"'
        types: [python]
        language: system

  - repo: local
    hooks:
      - id: flake8
        name: flake8
        entry: bash -c 'cd backend && poetry run flake8 --config setup.cfg "$@"'
        types: [python]
        language: system

  - repo: local
    hooks:
      - id: pylint
        name: pylint
        entry: bash -c 'cd backend && poetry run pylint --rcfile pyproject.toml "$@"'
        types: [python]
        language: system

  - repo: local
    hooks:
      - id: pytest
        name: pytest
        entry: bash -c 'cd backend && poetry run pytest -c pyproject.toml "$@"'
        types: [python]
        language: system
        pass_filenames: false
        always_run: true
