version: "3.7"

services:
  postgres:
    image: postgres
    container_name: pg-docker
    env_file:
      - .env
    environment:
      PGDATA: /data/postgres/
    volumes:
      - ./db_data:/data/postgres/
    ports:
      - "5432:5432"
    networks:
      - sit_igp_management_backend
    restart: unless-stopped

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin-docker
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@email.com
      PGADMIN_DEFAULT_PASSWORD: secret
    ports:
      - "5050:80"
    networks:
      - sit_igp_management_backend
    restart: unless-stopped

networks:
  sit_igp_management_backend:
    driver: bridge

