version: "3.7"

services:
  db:
    image: postgres
    env_file:
      - .env
    environment:
      - PGDATA=/data/postgres/
    volumes:
      - pg_data:/data/postgres/
    ports:
      - "5432:5432"
    networks:
      - sit_igp_management_backend
    restart: unless-stopped

  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@email.com
      - PGADMIN_DEFAULT_PASSWORD=secret
    volumes:
      - pgadmin_data:/root/.pgadmin
    ports:
      - "5050:80"
    networks:
      - sit_igp_management_backend
    restart: unless-stopped

  backend:
    build:
      context: .
      dockerfile: ./Dockerfile
    env_file:
      - .env
    environment:
      - POSTGRES_SERVER=db
    ports:
      - "8000:8000"
    depends_on:
      - db
    networks:
      - sit_igp_management_backend
    restart: on-failure

networks:
  sit_igp_management_backend:
    driver: bridge

volumes:
  pg_data: {}
  pgadmin_data: {}
