app = "api-sit-igp-management"
kill_signal = "SIGINT"
kill_timeout = 5
processes = []

[env]
APP_ENV = "prod"
AUTH_DOMAIN          = "sit-igp.jp.auth0.com"
AUTH_API_AUDIENCE    = "sit_igp_management_backend"
AUTH_ALGORITHMS      = "RS256"
AUTH_ISSUER          = "https://sit-igp.jp.auth0.com/"
AUTH_EMAIL_NAMESPACE = "https://sit-igp-management.com/email"
CORS_ALLOW_ORIGINS = ["https://sit-igp-management.vercel.app"]
SUPERUSER_FULLNAME = "Phan Xuan Tan"
SUPERUSER_EMAIL    = "tanpx@shibaura-it.ac.jp"
SENTRY_DSN = "https://53c2b54c5b7e4bb09f69aaf41ed2acd6@o1119301.ingest.sentry.io/6153617"
POSTGRES_SERVER = ""
POSTGRES_USER = ""
POSTGRES_PASSWORD = ""
POSTGRES_DB = ""
DATABASE_URL = "postgres://postgres:mDArzT4BhiKFqEO@db-sit-igp-management.internal:5432/app?sslmode=disable"

[experimental]
  auto_rollback = true

[[services]]
  http_checks = []
  internal_port = 8000
  processes = ["app"]
  protocol = "tcp"
  script_checks = []
  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

  [[services.ports]]
    force_https = true
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  [[services.tcp_checks]]
    grace_period = "1s"
    interval = "15s"
    restart_limit = 0
    timeout = "2s"
