# pylint: skip-file
# flake8: noqa

"""create_all_tables

Revision ID: 255e5c3a104e
Revises:
Create Date: 2022-01-16 12:20:58.919228+09:00

"""
import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision = "255e5c3a104e"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "professors",
        sa.Column("id_", sa.Integer(), nullable=False),
        sa.Column("is_deleted", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("full_name", sa.String(length=256), nullable=False),
        sa.Column("email", sa.String(length=256), nullable=False),
        sa.Column("is_verified", sa.Boolean(), nullable=False),
        sa.Column("is_superuser", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id_"),
    )
    op.create_index(
        op.f("ix_professors_created_at"),
        "professors",
        ["created_at"],
        unique=False,
    )
    op.create_index(op.f("ix_professors_email"), "professors", ["email"], unique=True)
    op.create_index(op.f("ix_professors_id_"), "professors", ["id_"], unique=True)
    op.create_index(
        op.f("ix_professors_is_deleted"),
        "professors",
        ["is_deleted"],
        unique=False,
    )
    op.create_table(
        "students",
        sa.Column("id_", sa.Integer(), nullable=False),
        sa.Column("is_deleted", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("full_name", sa.String(length=256), nullable=False),
        sa.Column("email", sa.String(length=256), nullable=True),
        sa.Column(
            "gender",
            sa.Enum("MALE", "FEMALE", "OTHER", name="gender"),
            nullable=True,
        ),
        sa.Column("area_of_study", sa.String(length=256), nullable=True),
        sa.Column("admission_date", sa.Date(), nullable=False),
        sa.Column("supervisor_id", sa.Integer(), nullable=True),
        sa.Column("advisor1_id", sa.Integer(), nullable=True),
        sa.Column("advisor2_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["advisor1_id"],
            ["professors.id_"],
        ),
        sa.ForeignKeyConstraint(
            ["advisor2_id"],
            ["professors.id_"],
        ),
        sa.ForeignKeyConstraint(
            ["supervisor_id"],
            ["professors.id_"],
        ),
        sa.PrimaryKeyConstraint("id_"),
        sa.UniqueConstraint("email"),
    )
    op.create_index(
        op.f("ix_students_admission_date"),
        "students",
        ["admission_date"],
        unique=False,
    )
    op.create_index(
        op.f("ix_students_created_at"),
        "students",
        ["created_at"],
        unique=False,
    )
    op.create_index(op.f("ix_students_id_"), "students", ["id_"], unique=True)
    op.create_index(
        op.f("ix_students_is_deleted"),
        "students",
        ["is_deleted"],
        unique=False,
    )
    op.create_table(
        "presentations",
        sa.Column("id_", sa.Integer(), nullable=False),
        sa.Column("is_deleted", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("student_id", sa.Integer(), nullable=False),
        sa.Column("presentation_date", sa.Date(), nullable=False),
        sa.Column("presentation_length", sa.String(), nullable=True),
        sa.Column("reviewer1_id", sa.Integer(), nullable=True),
        sa.Column("reviewer2_id", sa.Integer(), nullable=True),
        sa.Column("reviewer3_id", sa.Integer(), nullable=True),
        sa.Column("reviewer4_id", sa.Integer(), nullable=True),
        sa.Column("reviewer5_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["reviewer1_id"],
            ["professors.id_"],
        ),
        sa.ForeignKeyConstraint(
            ["reviewer2_id"],
            ["professors.id_"],
        ),
        sa.ForeignKeyConstraint(
            ["reviewer3_id"],
            ["professors.id_"],
        ),
        sa.ForeignKeyConstraint(
            ["reviewer4_id"],
            ["professors.id_"],
        ),
        sa.ForeignKeyConstraint(
            ["reviewer5_id"],
            ["professors.id_"],
        ),
        sa.ForeignKeyConstraint(
            ["student_id"],
            ["students.id_"],
        ),
        sa.PrimaryKeyConstraint("id_"),
    )
    op.create_index(
        op.f("ix_presentations_created_at"),
        "presentations",
        ["created_at"],
        unique=False,
    )
    op.create_index(op.f("ix_presentations_id_"), "presentations", ["id_"], unique=True)
    op.create_index(
        op.f("ix_presentations_is_deleted"),
        "presentations",
        ["is_deleted"],
        unique=False,
    )
    op.create_index(
        op.f("ix_presentations_presentation_date"),
        "presentations",
        ["presentation_date"],
        unique=False,
    )
    op.create_index(
        op.f("ix_presentations_student_id"),
        "presentations",
        ["student_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_presentations_student_id"), table_name="presentations")
    op.drop_index(op.f("ix_presentations_presentation_date"), table_name="presentations")
    op.drop_index(op.f("ix_presentations_is_deleted"), table_name="presentations")
    op.drop_index(op.f("ix_presentations_id_"), table_name="presentations")
    op.drop_index(op.f("ix_presentations_created_at"), table_name="presentations")
    op.drop_table("presentations")
    op.drop_index(op.f("ix_students_is_deleted"), table_name="students")
    op.drop_index(op.f("ix_students_id_"), table_name="students")
    op.drop_index(op.f("ix_students_created_at"), table_name="students")
    op.drop_index(op.f("ix_students_admission_date"), table_name="students")
    op.drop_table("students")
    op.drop_index(op.f("ix_professors_is_deleted"), table_name="professors")
    op.drop_index(op.f("ix_professors_id_"), table_name="professors")
    op.drop_index(op.f("ix_professors_email"), table_name="professors")
    op.drop_index(op.f("ix_professors_created_at"), table_name="professors")
    op.drop_table("professors")
    op.execute("DROP TYPE gender")
    # ### end Alembic commands ###
