# pylint: skip-file
# flake8: noqa

"""create_all_tables

Revision ID: 18039f0230b3
Revises: d6db8d619e77
Create Date: 2022-01-20 15:48:51.787339+09:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "18039f0230b3"
down_revision = "d6db8d619e77"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "presentation_evaluations",
        sa.Column("score_qa_ability", sa.Integer(), nullable=False),
    )
    op.add_column(
        "presentation_evaluations",
        sa.Column("question_score", sa.Float(), nullable=False),
    )
    op.drop_column("presentation_evaluations", "score_qa")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "presentation_evaluations",
        sa.Column("score_qa", sa.INTEGER(), autoincrement=False, nullable=False),
    )
    op.drop_column("presentation_evaluations", "question_score")
    op.drop_column("presentation_evaluations", "score_qa_ability")
    # ### end Alembic commands ###
