# pylint: skip-file
# flake8: noqa

"""semester_end_evaluations_tables

Revision ID: c4b64d6e51f5
Revises: f721c0ecb59e
Create Date: 2022-01-21 13:56:54.404780+09:00

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "c4b64d6e51f5"
down_revision = "f721c0ecb59e"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "lab_rotation_evaluations",
        sa.Column("id_", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("is_deleted", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column("presentation_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("course_score", sa.Float(), nullable=False),
        sa.ForeignKeyConstraint(
            ["presentation_id"],
            ["presentations.id_"],
        ),
        sa.PrimaryKeyConstraint("id_"),
    )
    op.create_index(
        op.f("ix_lab_rotation_evaluations_created_at"),
        "lab_rotation_evaluations",
        ["created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_lab_rotation_evaluations_id_"),
        "lab_rotation_evaluations",
        ["id_"],
        unique=True,
    )
    op.create_index(
        op.f("ix_lab_rotation_evaluations_is_deleted"),
        "lab_rotation_evaluations",
        ["is_deleted"],
        unique=False,
    )
    op.create_index(
        op.f("ix_lab_rotation_evaluations_presentation_id"),
        "lab_rotation_evaluations",
        ["presentation_id"],
        unique=False,
    )
    op.create_table(
        "lab_seminar_evaluations",
        sa.Column("id_", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("is_deleted", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column("presentation_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("score_daily_activities_1", sa.Float(), nullable=False),
        sa.Column("score_daily_activities_2", sa.Float(), nullable=False),
        sa.Column("score_meeting_presentation_1", sa.Float(), nullable=False),
        sa.Column("score_meeting_presentation_2", sa.Float(), nullable=False),
        sa.Column("course_score", sa.Float(), nullable=False),
        sa.ForeignKeyConstraint(
            ["presentation_id"],
            ["presentations.id_"],
        ),
        sa.PrimaryKeyConstraint("id_"),
    )
    op.create_index(
        op.f("ix_lab_seminar_evaluations_created_at"),
        "lab_seminar_evaluations",
        ["created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_lab_seminar_evaluations_id_"),
        "lab_seminar_evaluations",
        ["id_"],
        unique=True,
    )
    op.create_index(
        op.f("ix_lab_seminar_evaluations_is_deleted"),
        "lab_seminar_evaluations",
        ["is_deleted"],
        unique=False,
    )
    op.create_index(
        op.f("ix_lab_seminar_evaluations_presentation_id"),
        "lab_seminar_evaluations",
        ["presentation_id"],
        unique=False,
    )
    op.create_table(
        "thesis_program_evaluations",
        sa.Column("id_", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("is_deleted", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column("presentation_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("score_daily_activities_1", sa.Float(), nullable=False),
        sa.Column("score_daily_activities_2", sa.Float(), nullable=False),
        sa.Column("score_meeting_presentation_1", sa.Float(), nullable=False),
        sa.Column("score_meeting_presentation_2", sa.Float(), nullable=False),
        sa.Column("course_score", sa.Float(), nullable=False),
        sa.ForeignKeyConstraint(
            ["presentation_id"],
            ["presentations.id_"],
        ),
        sa.PrimaryKeyConstraint("id_"),
    )
    op.create_index(
        op.f("ix_thesis_program_evaluations_created_at"),
        "thesis_program_evaluations",
        ["created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_thesis_program_evaluations_id_"),
        "thesis_program_evaluations",
        ["id_"],
        unique=True,
    )
    op.create_index(
        op.f("ix_thesis_program_evaluations_is_deleted"),
        "thesis_program_evaluations",
        ["is_deleted"],
        unique=False,
    )
    op.create_index(
        op.f("ix_thesis_program_evaluations_presentation_id"),
        "thesis_program_evaluations",
        ["presentation_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_thesis_program_evaluations_presentation_id"),
        table_name="thesis_program_evaluations",
    )
    op.drop_index(
        op.f("ix_thesis_program_evaluations_is_deleted"),
        table_name="thesis_program_evaluations",
    )
    op.drop_index(
        op.f("ix_thesis_program_evaluations_id_"), table_name="thesis_program_evaluations"
    )
    op.drop_index(
        op.f("ix_thesis_program_evaluations_created_at"),
        table_name="thesis_program_evaluations",
    )
    op.drop_table("thesis_program_evaluations")
    op.drop_index(
        op.f("ix_lab_seminar_evaluations_presentation_id"),
        table_name="lab_seminar_evaluations",
    )
    op.drop_index(
        op.f("ix_lab_seminar_evaluations_is_deleted"),
        table_name="lab_seminar_evaluations",
    )
    op.drop_index(
        op.f("ix_lab_seminar_evaluations_id_"), table_name="lab_seminar_evaluations"
    )
    op.drop_index(
        op.f("ix_lab_seminar_evaluations_created_at"),
        table_name="lab_seminar_evaluations",
    )
    op.drop_table("lab_seminar_evaluations")
    op.drop_index(
        op.f("ix_lab_rotation_evaluations_presentation_id"),
        table_name="lab_rotation_evaluations",
    )
    op.drop_index(
        op.f("ix_lab_rotation_evaluations_is_deleted"),
        table_name="lab_rotation_evaluations",
    )
    op.drop_index(
        op.f("ix_lab_rotation_evaluations_id_"), table_name="lab_rotation_evaluations"
    )
    op.drop_index(
        op.f("ix_lab_rotation_evaluations_created_at"),
        table_name="lab_rotation_evaluations",
    )
    op.drop_table("lab_rotation_evaluations")
    # ### end Alembic commands ###
