# pylint: skip-file
# flake8: noqa

"""create_all_tables

Revision ID: d6db8d619e77
Revises: 
Create Date: 2022-01-20 12:33:39.980079+09:00

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "d6db8d619e77"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "professors",
        sa.Column("id_", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("is_deleted", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column("full_name", sa.String(length=256), nullable=False),
        sa.Column("email", sa.String(length=256), nullable=False),
        sa.Column("is_verified", sa.Boolean(), nullable=False),
        sa.Column("is_superuser", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id_"),
    )
    op.create_index(
        op.f("ix_professors_created_at"), "professors", ["created_at"], unique=False
    )
    op.create_index(op.f("ix_professors_email"), "professors", ["email"], unique=True)
    op.create_index(op.f("ix_professors_id_"), "professors", ["id_"], unique=True)
    op.create_index(
        op.f("ix_professors_is_deleted"), "professors", ["is_deleted"], unique=False
    )
    op.create_table(
        "students",
        sa.Column("id_", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("is_deleted", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column("full_name", sa.String(length=256), nullable=False),
        sa.Column("admission_date", sa.Date(), nullable=False),
        sa.Column("email", sa.String(length=256), nullable=True),
        sa.Column(
            "gender", sa.Enum("MALE", "FEMALE", "OTHER", name="gender"), nullable=True
        ),
        sa.Column("area_of_study", sa.String(length=2048), nullable=True),
        sa.Column("supervisor_id", postgresql.UUID(), nullable=True),
        sa.Column("advisor1_id", postgresql.UUID(), nullable=True),
        sa.Column("advisor2_id", postgresql.UUID(), nullable=True),
        sa.ForeignKeyConstraint(
            ["advisor1_id"],
            ["professors.id_"],
        ),
        sa.ForeignKeyConstraint(
            ["advisor2_id"],
            ["professors.id_"],
        ),
        sa.ForeignKeyConstraint(
            ["supervisor_id"],
            ["professors.id_"],
        ),
        sa.PrimaryKeyConstraint("id_"),
    )
    op.create_index(
        op.f("ix_students_admission_date"), "students", ["admission_date"], unique=False
    )
    op.create_index(
        op.f("ix_students_advisor1_id"), "students", ["advisor1_id"], unique=False
    )
    op.create_index(
        op.f("ix_students_advisor2_id"), "students", ["advisor2_id"], unique=False
    )
    op.create_index(
        op.f("ix_students_created_at"), "students", ["created_at"], unique=False
    )
    op.create_index(op.f("ix_students_email"), "students", ["email"], unique=True)
    op.create_index(op.f("ix_students_id_"), "students", ["id_"], unique=True)
    op.create_index(
        op.f("ix_students_is_deleted"), "students", ["is_deleted"], unique=False
    )
    op.create_index(
        op.f("ix_students_supervisor_id"), "students", ["supervisor_id"], unique=False
    )
    op.create_table(
        "presentations",
        sa.Column("id_", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("is_deleted", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column("student_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("presentation_date", sa.Date(), nullable=False),
        sa.Column("presentation_length", sa.String(length=256), nullable=True),
        sa.Column("session_chair_id", postgresql.UUID(as_uuid=True), nullable=True),
        sa.Column("reviewer1_id", postgresql.UUID(as_uuid=True), nullable=True),
        sa.Column("reviewer2_id", postgresql.UUID(as_uuid=True), nullable=True),
        sa.Column("reviewer3_id", postgresql.UUID(as_uuid=True), nullable=True),
        sa.Column("reviewer4_id", postgresql.UUID(as_uuid=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["reviewer1_id"],
            ["professors.id_"],
        ),
        sa.ForeignKeyConstraint(
            ["reviewer2_id"],
            ["professors.id_"],
        ),
        sa.ForeignKeyConstraint(
            ["reviewer3_id"],
            ["professors.id_"],
        ),
        sa.ForeignKeyConstraint(
            ["reviewer4_id"],
            ["professors.id_"],
        ),
        sa.ForeignKeyConstraint(
            ["session_chair_id"],
            ["professors.id_"],
        ),
        sa.ForeignKeyConstraint(
            ["student_id"],
            ["students.id_"],
        ),
        sa.PrimaryKeyConstraint("id_"),
    )
    op.create_index(
        op.f("ix_presentations_created_at"), "presentations", ["created_at"], unique=False
    )
    op.create_index(op.f("ix_presentations_id_"), "presentations", ["id_"], unique=True)
    op.create_index(
        op.f("ix_presentations_is_deleted"), "presentations", ["is_deleted"], unique=False
    )
    op.create_index(
        op.f("ix_presentations_presentation_date"),
        "presentations",
        ["presentation_date"],
        unique=False,
    )
    op.create_index(
        op.f("ix_presentations_reviewer1_id"),
        "presentations",
        ["reviewer1_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_presentations_reviewer2_id"),
        "presentations",
        ["reviewer2_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_presentations_reviewer3_id"),
        "presentations",
        ["reviewer3_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_presentations_reviewer4_id"),
        "presentations",
        ["reviewer4_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_presentations_session_chair_id"),
        "presentations",
        ["session_chair_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_presentations_student_id"), "presentations", ["student_id"], unique=False
    )
    op.create_table(
        "presentation_evaluations",
        sa.Column("id_", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("is_deleted", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column("presentation_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("reviewer_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("score_research_goal", sa.Integer(), nullable=False),
        sa.Column("score_delivery", sa.Integer(), nullable=False),
        sa.Column("score_visual_aid", sa.Integer(), nullable=False),
        sa.Column("score_time", sa.Integer(), nullable=False),
        sa.Column("score_qa", sa.Integer(), nullable=False),
        sa.Column("comment", sa.String(length=256), nullable=True),
        sa.ForeignKeyConstraint(
            ["presentation_id"],
            ["presentations.id_"],
        ),
        sa.ForeignKeyConstraint(
            ["reviewer_id"],
            ["professors.id_"],
        ),
        sa.PrimaryKeyConstraint("id_"),
    )
    op.create_index(
        op.f("ix_presentation_evaluations_created_at"),
        "presentation_evaluations",
        ["created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_presentation_evaluations_id_"),
        "presentation_evaluations",
        ["id_"],
        unique=True,
    )
    op.create_index(
        op.f("ix_presentation_evaluations_is_deleted"),
        "presentation_evaluations",
        ["is_deleted"],
        unique=False,
    )
    op.create_index(
        op.f("ix_presentation_evaluations_presentation_id"),
        "presentation_evaluations",
        ["presentation_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_presentation_evaluations_reviewer_id"),
        "presentation_evaluations",
        ["reviewer_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_presentation_evaluations_reviewer_id"),
        table_name="presentation_evaluations",
    )
    op.drop_index(
        op.f("ix_presentation_evaluations_presentation_id"),
        table_name="presentation_evaluations",
    )
    op.drop_index(
        op.f("ix_presentation_evaluations_is_deleted"),
        table_name="presentation_evaluations",
    )
    op.drop_index(
        op.f("ix_presentation_evaluations_id_"), table_name="presentation_evaluations"
    )
    op.drop_index(
        op.f("ix_presentation_evaluations_created_at"),
        table_name="presentation_evaluations",
    )
    op.drop_table("presentation_evaluations")
    op.drop_index(op.f("ix_presentations_student_id"), table_name="presentations")
    op.drop_index(op.f("ix_presentations_session_chair_id"), table_name="presentations")
    op.drop_index(op.f("ix_presentations_reviewer4_id"), table_name="presentations")
    op.drop_index(op.f("ix_presentations_reviewer3_id"), table_name="presentations")
    op.drop_index(op.f("ix_presentations_reviewer2_id"), table_name="presentations")
    op.drop_index(op.f("ix_presentations_reviewer1_id"), table_name="presentations")
    op.drop_index(op.f("ix_presentations_presentation_date"), table_name="presentations")
    op.drop_index(op.f("ix_presentations_is_deleted"), table_name="presentations")
    op.drop_index(op.f("ix_presentations_id_"), table_name="presentations")
    op.drop_index(op.f("ix_presentations_created_at"), table_name="presentations")
    op.drop_table("presentations")
    op.drop_index(op.f("ix_students_supervisor_id"), table_name="students")
    op.drop_index(op.f("ix_students_is_deleted"), table_name="students")
    op.drop_index(op.f("ix_students_id_"), table_name="students")
    op.drop_index(op.f("ix_students_email"), table_name="students")
    op.drop_index(op.f("ix_students_created_at"), table_name="students")
    op.drop_index(op.f("ix_students_advisor2_id"), table_name="students")
    op.drop_index(op.f("ix_students_advisor1_id"), table_name="students")
    op.drop_index(op.f("ix_students_admission_date"), table_name="students")
    op.drop_table("students")
    op.drop_index(op.f("ix_professors_is_deleted"), table_name="professors")
    op.drop_index(op.f("ix_professors_id_"), table_name="professors")
    op.drop_index(op.f("ix_professors_email"), table_name="professors")
    op.drop_index(op.f("ix_professors_created_at"), table_name="professors")
    op.drop_table("professors")
    # ### end Alembic commands ###
