# pylint: skip-file
# flake8: noqa

"""presentation_evaluations_comment

Revision ID: e35113d3ba7c
Revises: c4b64d6e51f5
Create Date: 2022-01-25 11:29:01.806308+09:00

"""
import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision = "e35113d3ba7c"
down_revision = "c4b64d6e51f5"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(
        "ALTER TABLE presentation_evaluations ALTER COLUMN comment TYPE character varying(1000000);"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
